# Generated by Django 6.1.1 on 2026-09-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogpost_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('main_complaint', models.TextField(help_text='Primary health concern or symptom')),
                ('duration', models.CharField(help_text='How long have you had this?', max_length=100)),
                ('severity', models.CharField(help_text='Mild, Moderate, Severe, etc.', max_length=50)),
                ('modalities', models.TextField(help_text='What makes it better or worse?')),
                ('past_conditions', models.TextField(blank=True, help_text='Past illnesses or surgeries', null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, help_text='Relevant family medical history', null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('previous_treatments', models.TextField(blank=True, help_text='What have you tried so far?', null=True)),
                ('sleep_appetite_emotions', models.TextField(help_text='Sleep patterns, appetite, thirst, thermal reactions, emotional state, and lifestyle')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
