# Generated by Django 6.1.1 on 2026-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_consultationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Unique URL path (auto-filled or manual)', max_length=200, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Respiratory, Musculoskeletal, Skin', max_length=100, null=True)),
                ('summary', models.TextField(help_text='Brief overview of the condition')),
                ('detailed_description', models.TextField(help_text='Comprehensive description, homeopathic approach, and key characteristics')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
