# Generated by Django 6.1.1 on 2026-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diseases/'),
        ),
    ]
