# Generated by Django 6.1.1 on 2026-09-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_disease_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Full patient story for the detail page', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL path (auto-filled)', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief description for the flash card grid', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review_text',
            field=models.TextField(help_text='Legacy review field (optional)'),
        ),
    ]
